cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESSKEY}
      secret-key: ${AWS_SECRETKEY}
    region:
      static: sa-east-1
    stack:
      auto: false

application:
  bucket:
    name: vilayaraimagens

server:
  port: 8080