cloud:
  aws:
    credentials:
      access-key: AKIATARQ4F5VYQMVL7MN
      secret-key: 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
    region:
      static: sa-east-1
    stack:
      auto: false

application:
  bucket:
    name: vilayaraimagens

server:
  port: 8080